---
title: "Homework 2"
author: E. Brennan Bollman
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1

Step 1: Read the Mr. Trashwheel dataset, with clean names, omitting non-data entries and values that are not dumpster-specific.

```{r}
trashwheel_df = 
  read_xlsx(
    "./data/Trash-wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

Step 2: Read the precipitation data for 2017 and 2018. 

```{r}
precip_2018 = 
  read_excel(
    "./data/Trash-wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2017 = 
  read_excel(
    "./data/Trash-wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Step 3: Combine annual precipitation. Convert month from dbl to character variable.

```{r}
precip_df = 
  bind_rows(precip_2018, precip_2017)

month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

left_join(precip_df, month_df, by = "month") %>% 
  select(-month)
```

